var url = window.location.pathname;
if(url.endsWith("index.php")){
    document.getElementById("index.php").classList.add("active");
    document.getElementById("index.php").classList.remove("a1");
}
if(url.endsWith("favs.php")){
    document.getElementById("favs.php").classList.add("active");
    document.getElementById("favs.php").classList.remove("a1");
}
if(url.endsWith("usuarios.php")){
    document.getElementById("usuarios.php").classList.add("active");
    document.getElementById("usuarios.php").classList.remove("a1");
}
if(url.endsWith("libros.php")){
    document.getElementById("libros.php").classList.add("active");
    document.getElementById("libros.php").classList.remove("a1");
}
if(url.endsWith("cuenta.php")){
    document.getElementById("cuenta.php").classList.add("active");
    document.getElementById("cuenta.php").classList.remove("a1");
}